[workspace]
authors = ["Nabil-Fareed Alikhan <nabil@happykhan.com>"]
channels = ["conda-forge", "bioconda"]
name = "bactscout"
platforms = ["osx-64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
bactscout="python bactscout.py"
# Developer tasks
lint="pixi run -e dev ruff check ."
format="pixi run -e dev ruff format ."
check="pixi run -e dev ruff check --fix . && ruff format ."
test="pixi run -e dev python -m pytest tests/ -v"
test-cov="pixi run -e dev python -m pytest tests/ --cov=bactscout --cov-report=term-missing --cov-report=html --cov-report=xml"
cov-report="pixi run -e dev python -m coverage html && python -m coverage report"
# Docs tasks now automatically run inside the `docs` environment
docs="pixi run -e docs -- mkdocs serve"
docs-build="pixi run -e docs -- mkdocs build --strict"

[feature.dev.tasks]
build-conda="conda-build conda"

[dependencies]
fastp = ">=1.0.1,<2"
sylph = ">=0.8.1,<0.9"
pixi-pack = ">=0.7.3,<0.8"
nextflow = ">=24.0.0,<25"
python = ">=3.9,<3.12"

[pypi-dependencies]
typer = ">=0.19.2, <0.20"
rich = ">=14.1.0, <15"
pyaml = ">=25.7.0, <26"
psutil = ">=7.1.0, <8"
stringmlst = ">=0.6.3, <0.7"
requests = ">=2.32.5, <3"

[feature.dev.dependencies]
conda-build = "*"

[feature.dev.pypi-dependencies]
ruff = ">=0.6.0, <0.7"
pytest = ">=8.0.0, <9.0"
coverage = ">=7.0.0, <8.0"
pytest-cov = ">=5.0.0, <6.0"
pytest-xdist = ">=3.5.0, <4.0"

[feature.docs.pypi-dependencies]
mkdocs = ">=1.6.0, <1.7"
mkdocs-material = ">=9.4.0, <10"
mkdocstrings = ">=0.25.0, <0.26"
mkdocstrings-python = ">=1.10.0, <1.11"
pymdown-extensions = ">=10.5, <11"

[environments]
dev = ["dev"]
docs = ["docs"]
